# Generated by Django 5.2 on 2025-06-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('added_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
