# Generated by Django 5.2 on 2025-07-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_message_patient_alter_message_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paymentstatus',
            field=models.CharField(choices=[('Unpaid', 'unpaid'), ('Paid', 'paid')], default='unpaid', max_length=10),
        ),
    ]
