# Generated by Django 5.2 on 2025-07-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_appointment_paymentstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_number', models.CharField(max_length=100)),
                ('transaction_date', models.CharField(max_length=20)),
                ('result_code', models.IntegerField()),
                ('checkout_request_id', models.CharField(max_length=100)),
            ],
        ),
    ]
