export const ActionTypes = {
  SET_DEPARTMENTS: "SET_DEPARTMENTS",
  SET_DOCTORS: "SET_DOCTORS",
  SET_APPOINTMENTS: "SET_APPOINTMENTS",
  SET_DOCTORAPPOINTMENTS: "SET_DOCTORAPPOINTMENTS",
  SET_SPECIALIZATIONS: "SET_SPECIALIZATIONS",
  SET_ROOMS: "SET_ROOMS",
};
