# Generated by Django 5.2 on 2025-05-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='doctor_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
