# Generated by Django 5.2 on 2026-04-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='doctor_number',
            new_name='staff_number',
        ),
    ]
