# Generated by Django 5.2 on 2026-04-03 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_rename_doctor_number_customuser_staff_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='staff_number',
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
