# Generated by Django 5.2 on 2025-04-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordetail',
            old_name='name',
            new_name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctordetail',
            name='email',
        ),
    ]
